update=21.01.2016 15:55:49
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=D:/mcu/kicad_library
[eeschema/libraries]
LibName1=stm32
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/Altera
LibName8=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName10=C:/Program Files/KiCad/share/kicad/library/atmel
LibName11=C:/Program Files/KiCad/share/kicad/library/audio
LibName12=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName13=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName14=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName15=C:/Program Files/KiCad/share/kicad/library/conn
LibName16=C:/Program Files/KiCad/share/kicad/library/contrib
LibName17=C:/Program Files/KiCad/share/kicad/library/cypress
LibName18=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName19=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName20=C:/Program Files/KiCad/share/kicad/library/diode
LibName21=C:/Program Files/KiCad/share/kicad/library/display
LibName22=C:/Program Files/KiCad/share/kicad/library/dsp
LibName23=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName24=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName25=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName26=C:/Program Files/KiCad/share/kicad/library/gennum
LibName27=C:/Program Files/KiCad/share/kicad/library/graphic
LibName28=C:/Program Files/KiCad/share/kicad/library/hc11
LibName29=C:/Program Files/KiCad/share/kicad/library/intel
LibName30=C:/Program Files/KiCad/share/kicad/library/interface
LibName31=C:/Program Files/KiCad/share/kicad/library/ir
LibName32=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName33=C:/Program Files/KiCad/share/kicad/library/linear
LibName34=C:/Program Files/KiCad/share/kicad/library/logo
LibName35=C:/Program Files/KiCad/share/kicad/library/maxim
LibName36=C:/Program Files/KiCad/share/kicad/library/memory
LibName37=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName38=C:/Program Files/KiCad/share/kicad/library/microchip
LibName39=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName40=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName41=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName42=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName45=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName46=C:/Program Files/KiCad/share/kicad/library/motorola
LibName47=C:/Program Files/KiCad/share/kicad/library/msp430
LibName48=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName49=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName50=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName51=C:/Program Files/KiCad/share/kicad/library/opto
LibName52=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName53=C:/Program Files/KiCad/share/kicad/library/philips
LibName54=C:/Program Files/KiCad/share/kicad/library/power
LibName55=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName56=C:/Program Files/KiCad/share/kicad/library/powerint
LibName57=C:/Program Files/KiCad/share/kicad/library/pspice
LibName58=C:/Program Files/KiCad/share/kicad/library/references
LibName59=C:/Program Files/KiCad/share/kicad/library/regul
LibName60=C:/Program Files/KiCad/share/kicad/library/relays
LibName61=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName62=C:/Program Files/KiCad/share/kicad/library/sensors
LibName63=C:/Program Files/KiCad/share/kicad/library/silabs
LibName64=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName65=C:/Program Files/KiCad/share/kicad/library/stm8
LibName66=C:/Program Files/KiCad/share/kicad/library/supertex
LibName67=C:/Program Files/KiCad/share/kicad/library/switches
LibName68=C:/Program Files/KiCad/share/kicad/library/texas
LibName69=C:/Program Files/KiCad/share/kicad/library/transf
LibName70=C:/Program Files/KiCad/share/kicad/library/transistors
LibName71=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName72=C:/Program Files/KiCad/share/kicad/library/valves
LibName73=C:/Program Files/KiCad/share/kicad/library/video
LibName74=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName75=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName76=D:/mcu/kicad-library/library/Worldsemi
LibName77=D:/mcu/kicad-library/library/device
LibName78=D:/mcu/kicad-library/library/yaqwsx
