#!/usr/bin/python
import hal, serial, json

POT_COUNT = 10

port = "/dev/temperature"

h = hal.component("pots")
for i in range(0, POT_COUNT):
	h.newpin("POT" + str(i), hal.HAL_S32, hal.HAL_OUT)
h.ready()

for i in range(0, POT_COUNT):
	h["POT" + str(i)] = 0
try:
    s = serial.Serial(port, baudrate=115200)
    while 1:
        pot, value = tuple(s.readline().split(":"))
        if i >= POT_COUNT:
              continue
        h[pot] = int(float(value) * 100)
        print("Setting " + pot + ": " + str(float(value) * 100))
except KeyboardInterrupt:
    raise SystemExit
